backend:
  name: github
  repo: andrevvm/john-moods
  branch: live
  site_domain: stoic-kalam-384ed4.netlify.com

media_folder: "site/images/uploads"

collections:
  - name: settings
    label: Content
    create: false
    files:
      - file: site/_data/about.yml
        label: About
        name: about
        fields:
          - label: Text
            name: text
            widget: markdown
      - file: site/_data/videos.yml
        label: Videos
        name: videos
        fields:
          - label: Embeds
            name: embeds
            widget: markdown
      - file: site/_data/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Intro background
            name: intro_bg
            widget: color
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: id, hint: "ID for page to open when clicked", widget: string}
              - { label: 'Background', name: 'bg', widget: color }
              - { label: 'Text', name: 'text', widget: color }